# Generated by Django 3.0.3 on 2020-03-08 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Test_Id', models.IntegerField()),
                ('Question', models.CharField(max_length=200)),
                ('Answer', models.CharField(max_length=10)),
            ],
        ),
    ]
