# Generated by Django 3.0.3 on 2020-03-08 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Career', '0002_auto_20200308_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='tests',
            name='Option',
            field=models.TextField(default=0),
        ),
    ]
