# Generated by Django 3.0.3 on 2020-03-14 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Career', '0003_tests_option'),
    ]

    operations = [
        migrations.CreateModel(
            name='General_Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Test_Id', models.IntegerField()),
                ('Question', models.TextField()),
                ('Option', models.TextField(default=0)),
                ('Answer', models.CharField(max_length=10)),
            ],
        ),
    ]
