# Generated by Django 3.0.3 on 2020-05-13 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Career', '0006_college'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='fee',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='college',
            name='rating',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='college',
            name='salary',
            field=models.TextField(),
        ),
    ]
