# Generated by Django 3.0.3 on 2020-05-13 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Career', '0007_auto_20200513_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='C_img',
            field=models.TextField(default='https://upload.wikimedia.org/wikipedia/commons/1/1a/Chapin_Hall%2C_Williams_College_-_Williamstown%2C_Massachusetts.jpg'),
        ),
    ]
