# Generated by Django 3.0.3 on 2020-05-14 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Career', '0008_college_c_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Placements', models.TextField()),
                ('Infrastructure', models.TextField()),
                ('Faculty_Course_Curriculum', models.TextField()),
                ('Crowd_Campus_Life', models.TextField()),
                ('Value_for_Money', models.TextField()),
            ],
        ),
    ]
