# Generated by Django 3.0.3 on 2020-05-14 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Career', '0009_ratings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('C_id', models.IntegerField()),
                ('name', models.TextField()),
                ('designation', models.TextField()),
                ('rate', models.TextField()),
                ('comment', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='ratings',
            name='C_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
