# Generated by Django 3.0.3 on 2020-05-14 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Career', '0010_auto_20200514_1912'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ratings',
        ),
        migrations.AddField(
            model_name='college',
            name='Crowd_Campus_Life',
            field=models.TextField(default='4.0'),
        ),
        migrations.AddField(
            model_name='college',
            name='Faculty_Course_Curriculum',
            field=models.TextField(default='4.0'),
        ),
        migrations.AddField(
            model_name='college',
            name='Infrastructure',
            field=models.TextField(default='4.0'),
        ),
        migrations.AddField(
            model_name='college',
            name='Placements',
            field=models.TextField(default='4.0'),
        ),
        migrations.AddField(
            model_name='college',
            name='Value_for_Money',
            field=models.TextField(default='4.0'),
        ),
    ]
